# Generated by Django 5.0.1 on 2024-01-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('photo', models.CharField(max_length=255, null=True)),
                ('tag', models.CharField(choices=[('py', 'Python'), ('php', 'Php'), ('lg', 'Langage'), ('pol', 'Politique'), ('sp', 'Sport')], max_length=10, null=True)),
            ],
        ),
    ]
